/**
 * CKLB exporter — STIG Viewer 3 / eMASS native JSON checklist format.
 *
 * `.cklb` is the JSON successor to the legacy XML `.ckl` format. It carries
 * the same data but is much easier for downstream systems (eMASS, STIG Viewer
 * 3, Evaluate-STIG) to parse and merge.
 *
 * Schema reference: https://github.com/NSWCCDDC/cklb (DISA-published).
 */

interface MachineLike {
  id: string;
  name: string;
  osType?: string;
  osVersion?: string;
  hostname?: string;
  ipAddress?: string;
  macAddress?: string;
  fqdn?: string;
}
interface FindingLike {
  id: string;
  controlId: string;
  status: string;
  severity?: string;
  comments?: string;
  findingDetails?: string;
  mappingChain?: any;
}
interface ControlLike {
  id: string;
  vulnNum?: string;
  ruleId?: string;
  groupTitle?: string;
  ruleTitle?: string;
  discussion?: string;
  checkContent?: string;
  fixText?: string;
  severity?: string;
  ccis?: string[];
  legacyIds?: string[];
  stigBenchmarkId?: string;
  stigBenchmarkVersion?: string;
}

export function generateCklb(machine: MachineLike, findings: FindingLike[], controls: ControlLike[]): any {
  const controlById = new Map(controls.map((c) => [c.id, c]));

  // Determine the dominant STIG benchmark from the findings.
  const benchmarks = new Map<string, { id: string; version: string; rules: any[] }>();

  for (const f of findings) {
    const c = controlById.get(f.controlId);
    if (!c) continue;
    const bId  = c.stigBenchmarkId      || f.mappingChain?.stigBenchmarkId      || 'Unknown_STIG';
    const bVer = c.stigBenchmarkVersion || f.mappingChain?.stigBenchmarkVersion || 'V1R1';
    const key  = `${bId}|${bVer}`;
    if (!benchmarks.has(key)) benchmarks.set(key, { id: bId, version: bVer, rules: [] });
    benchmarks.get(key)!.rules.push({
      uuid: f.id,
      stig_uuid: c.id,
      target_key: null,
      stig_ref: null,
      group_id_src: c.vulnNum || c.id,
      group_tree: [{ id: c.vulnNum || c.id, type: 'Group', title: c.groupTitle || c.ruleTitle || '' }],
      group_id: c.vulnNum || c.id,
      severity: (f.severity || c.severity || 'medium').toLowerCase(),
      group_title: c.groupTitle || c.ruleTitle || '',
      rule_id_src: c.ruleId || c.id,
      rule_id:     c.ruleId || c.id,
      rule_version: c.stigBenchmarkVersion || 'V1R1',
      rule_title: c.ruleTitle || '',
      fix_text:   c.fixText || '',
      weight: '10.0',
      classification: 'Unclassified',
      ia_controls: '',
      false_positives: '',
      false_negatives: '',
      discussion: c.discussion || '',
      check_content: c.checkContent || '',
      documentable: false,
      mitigations: '',
      potential_impacts: '',
      third_party_tools: '',
      mitigation_control: '',
      responsibility: '',
      security_override_guidance: '',
      ccis: c.ccis || [],
      legacy_ids: c.legacyIds || [],
      group_check_text: c.checkContent || '',
      reference_identifier: c.vulnNum || c.id,
      status: mapStatus(f.status),
      overrides: {},
      comments: f.comments || '',
      finding_details: f.findingDetails || '',
    });
  }

  return {
    title: `${machine.name} STIG Checklist`,
    id: machine.id,
    active: true,
    mode: 1,
    has_path: true,
    target_data: {
      target_type: 'Computing',
      host_name: machine.hostname || machine.name,
      ip_address: machine.ipAddress || '',
      mac_address: machine.macAddress || '',
      fqdn: machine.fqdn || machine.name,
      comments: '',
      role: 'None',
      is_web_database: false,
      technology_area: '',
      web_db_site: '',
      web_db_instance: '',
    },
    stigs: Array.from(benchmarks.values()).map((b) => ({
      stig_name: b.id,
      display_name: b.id.replace(/_/g, ' '),
      stig_id: b.id,
      version: b.version,
      release_info: `Generated by Azure STIG Dashboard on ${new Date().toISOString()}`,
      uuid: `${b.id}-${b.version}`,
      reference_identifier: b.id,
      size: b.rules.length,
      rules: b.rules,
    })),
    cklb_version: '1.0',
  };
}

function mapStatus(s: string): string {
  switch ((s || '').toLowerCase()) {
    case 'open':            return 'open';
    case 'not_a_finding':   return 'not_a_finding';
    case 'not_applicable':  return 'not_applicable';
    default:                return 'not_reviewed';
  }
}
